### ISSUE TITLE
[SOLVED] [Linux] Out of sync sound on Goblins Quest 3 intro

### ISSUE THREAD

**Issue by mrmatteastwood** [diablodiab/scummvm#3]
**Steps to Reproduce**
1. Launch Goblins Quest 3 (e.g., GOG version) using ScummVM 2.3.0git on RetroArch 1.9.7 on Linux Mint
2. Watch intro

**Expected Results**
The intro should play correctly.

**Current Results**
The audio of the intro video is out of sync.

**Notes**
- Issue also occurs on ScummVM version available in the official RA repos (2.1)
- Issue only occurs on Linux. When running on Windows 10, audio is fine.
- Video: https://youtu.be/ikAUoGXWELM

**Comment by diablodiab** [comment]
Does the audio play in sync in official ScummVM for Linux?

**Comment by mrmatteastwood** [comment]
Actually, yeah it does. The issue only occurs on RA. I'm gonna experiment with audio latency settings when I have a chance (possibly later today).

**Comment by mrmatteastwood** [comment]
Changing audio latency does not make any difference :-/

**Comment by i30817** [comment]
I had a similar but harsher problem with a game from the same studio and same era and this commit fixed it:

https://github.com/libretro/scummvm/commit/09c856d7751bcfa67cff6474a0e74957a6f1582b

which comes from this PR:
https://github.com/libretro/scummvm/pull/110

that has a lot more information.

**Comment by mrmatteastwood** [comment]
Hmmmm, very interesting! I see this is from 3 years ago. However, I just tried on a recent build from the buildbot that @diablodiab maintains, and the issue still persists for me on Linux Mint. So did this fix ever make it into any version of the ScummVM core?

**Comment by i30817** [comment]
Sorry about the lack of response, i got the net cutoff because of limits. Anyway, yes, it was merged, but it's a indication 'not all is well' in the land of embedding scummvm, which isn't anything new to many retroarch cores because retroarch and the upstream always fights about what _is_ proper 'timing' because RA wants to do tricky things like runahead or frame advance or fast forward or a lot of other stuff that requires total control of the game video loop.

**Comment by i30817** [comment]
BTW that commit followup later introduced a 'optional timing hack'. I'd make sure that is not on. If it's not, id them, if i was feeling masochistic, look into the scummvm sources to see if the game used the function (the answer is apparently yes from the original commit) and _only_ that function to synchronize timing.

Another option is retroarch itself getting into a situation where the game 'expects' 60 hertz, and retroarch is running at something weird, like the recently committed fix where cores where keeping stale refresh rates from other cores or not updating (i can't quite recall what): https://github.com/libretro/RetroArch/pull/13316

**Comment by mrmatteastwood** [comment]
Hey @i30817, your explanations gave me an idea. I remembered that a good while back, I enabled the Speed Hack option in the ScummVM core options for Monkey Island 2. I just disabled that for Goblins Quest 3 and voilà, now the sound is in sync! Thanks for taking the time to respond in so much detail and for nudging me in the right direction.
