### ISSUE TITLE
Themes not loading

### ISSUE THREAD

**Issue by mrfixit2001** [diablodiab/scummvm#9]
I've tried following the process outlined here:
https://docs.libretro.com/library/scummvm/

But the themes don't load. I've tired the zip file from this build as well as the zip from the libretro site. Tried multiple locations for the paths as well. No matter what the classic theme is the only option.

**Comment by i30817** [comment]
They actually do, what's wrong is that you're not unzipping the right version of the data on the system/scummvm dir **or** starting the core manually and filling in the theme directory.

I should also add that path to the scummvm.ini file in my project libretro-mkscumm though, thanks for reminding me. 

The right version if you're using the buildbot also comes from the buildbot btw, and if you're building yourself, comes from building the zip and unzipping it on the system/scummvm dir (the zip already has scummvm dir inside so it's just unzipping it on system though).

Edit: this is the wrong repository to give this advice too. Don't build this, either use the buildbot at [build.bot.nu/nightly/](http://build.bot.nu/nightly/) to download the core and the extra scummvm files (ScummVM.zip) and place/extract them in the right directories or build the core at https://github.com/diablodiab/libretro-scummvm-backend (place it in the scummvm upstream in the right dir, follow the readme there) and those extra files (and place them in the right directory - do *not* build scummvm by calling make on the top level, just on the backends/platform/libretro dir).

**Comment by i30817** [comment]
E

**Comment by hizzlekizzle** [comment]
It seems to work fine with stuff taken directly from the upstream repo, so i guess we need to just re-package everything for the updated core.

**Comment by mrfixit2001** [comment]
Closing this now that the repo over at libretro has been updated to a more recent scummvm commit.
Confirmed it works with the proper settings in scummvm.ini.

Thanks for this fork! It provided a much needed update until the other folks caught up!
